### ISSUE TITLE
request to add resolve

### ISSUE THREAD

**Issue by rdeane** [kernsuite/packaging#160]
...while I'm at it, it would be great to add this if easily done: 

https://github.com/henrikju/resolve

Thanks.

**Comment by landmanbester** [comment]
This version of resolve is very outdated and probably shouldn't be packaged. Unfortunately, the latest version isn't publically available yet (although I believe this will change fairly soon). It will rely on NIFTy, the latest publically available version of which can be found here

https://gitlab.mpcdf.mpg.de/ift/NIFTy

which would be a valuable addition.

**Comment by gijzelaerr** [comment]
@Athanaseus how is this going? any progress? are you stuck?

**Comment by Athanaseus** [comment]
@gijzelaerr, yes I'm still stuck. Should I perhaps open an issue on the public repo to request a more updated public repo since they seem to be working actively on the private one (which I don't have access to neither).

**Comment by gijzelaerr** [comment]
@landmanbester what do you think?

**Comment by landmanbester** [comment]
NIFTy5, the latest stable release, would be a good addition. Have a look here https://gitlab.mpcdf.mpg.de/ift/nifty. If you get stuck I can put you in touch with the maintainers

**Comment by gijzelaerr** [comment]
nifty has been uploaded to KERN-dev, KERN4, and KERN-5. How is resolve doing @Athanaseus ?

**Comment by landmanbester** [comment]
Which version are you referring to? As far as I am aware the publically available version of resolve is outdated and should not be packaged

**Comment by Athanaseus** [comment]
According to @landmanbester it's pointless to have the current public version, and that we should probably wait for an updated release. Unless package it anyways and make updates as new stuff come on board?

**Comment by gijzelaerr** [comment]
ok @landmanbester please let us know when a new version is available.

**Comment by gijzelaerr** [comment]
@landmanbester did a new version become available?

**Comment by landmanbester** [comment]
I think NIFTy 5 is still the latest stable release

**Comment by gijzelaerr** [comment]
I think this is about the `resolve` package

**Comment by landmanbester** [comment]
I will check with Philipp and get back to you

**Comment by gijzelaerr** [comment]
hi @landmanbester any updates on this? thanks

**Comment by phiadaarr** [comment]
Thanks so much for your interest in putting resolve into KERN! I was not aware of this thread before but now I can answer you directly.

Just some hours ago we released the official version of NIFTy6 (https://gitlab.mpcdf.mpg.de/ift/nifty/) so that might be a candidate for packaging. Also we have a branch called `NIFTy_7` which functions as development branch until release. If you have packaged NIFTy5, then it might be a good idea to add/switch to NIFTy6 now.

Concerning `resolve`, I will discuss with @landmanbester in which form he imagines to have it in KERN.

**Comment by gijzelaerr** [comment]
hi @phara92 thanks for your input. Could you maybe also make a release tag for the 6.0 branch? We prefer to work with tagged releases so we avoid ambiguously.

**Comment by phiadaarr** [comment]
I have added the tag `6.0_kern` to the nifty repository. Please let me know if you need further input.

https://gitlab.mpcdf.mpg.de/ift/nifty/-/tags/6.0_kern

**Comment by gijzelaerr** [comment]
thanks @phara92 ! How hard are the scipy and bumpy requirements? 

the setup.py states: `scipy>=1.4.1` and `numpy>=1.17`

Ubuntu Bionic (18.04, our current KERN-6 target) comes with scipy 0.19 and numpy 1.13. Even the recently release Ubuntu Focal (20.04) doesn't have a recent enough scipy if this is really required. SO question is, do you really need such new scipy and numpy?

**Comment by phiadaarr** [comment]
Yes, we do. The two features we use which I can think of now are:

- We need the new random number generator interface of numpy (https://numpy.org/doc/stable/release/1.17.0-notes.html#new-extensible-numpy-random-module-with-selectable-random-number-generators).

- scipy 1.4 is used for the new FFT (https://docs.scipy.org/doc/scipy/reference/release.1.4.0.html#scipy-fft-added) which has been significantly improved there.

**Comment by gijzelaerr** [comment]
ok, thanks. Unfortunately, that means we can't package nifty, even for Ubuntu 20.04, which is a bit sad. 

You can make a pip installable binary wheel though, which is a more flexible approach for distribution your software.

**Comment by phiadaarr** [comment]
Are you actually sure that Ubuntu 20.04 comes with a 3.5-year-old scipy release (https://github.com/scipy/scipy/releases/tag/v0.19.1)? This sounds strange.

**Comment by gijzelaerr** [comment]
No, focal comes with 1.3.3:

https://packages.ubuntu.com/focal/python3-scipy

**Comment by phiadaarr** [comment]
Ahh, and it comes with numpy 1.17. If we have scipy 1.3.3 and additionally pypocketfft (https://gitlab.mpcdf.mpg.de/mtr/pypocketfft) that would work as well.

**Comment by gijzelaerr** [comment]
We could try that, but the holistic question is if it really is better to have a KERN package compared to a binary wheel. If you want to be KERN compatible you are going to limit yourself in new functionality, while a binary wheel probably offers much more flexibility.

I mean, I would love to add nifty to KERN, but because of the delay in python packaging updates, it isn't necessarily the best fit.

**Comment by gijzelaerr** [comment]
@phara92 @landmanbester working on KERN-7, do you guys think we should givet his a try?

**Comment by phiadaarr** [comment]
Yes! I have created a new tag for you: https://gitlab.mpcdf.mpg.de/ift/nifty/-/tags/6.0_kern
If you like to release KERN-7 soon that would be the version to go for. What are your time scales for the release of KERN-7?

**Comment by gijzelaerr** [comment]
the time scale is ASAP :)

**Comment by gijzelaerr** [comment]
ok above comments still apply, we are building KERN-7 for focal, which comes with numpy 1.16.5 and scipy 1.3.3. So unless you can modify nifty to support these versions I can't make a debian packages for focal.

**Comment by phiadaarr** [comment]
Given that installing nifty is a one-liner with `pip` and relies on numpy and scipy versions that many people have in their home folders anyways, I would suggest to delay including nifty into KERN.
Backporting nifty to the state of the art of Dec 2019, especially given that the performance and accuracy of the FFT implementations have been improved so much in the meantime, does not feel like a sensible time investment.

> the time scale is ASAP :)

There has been silence on this thread for months. Please let me now earlier when something needs to be done for KERN-8. Working with "ASAP" time scales is not healthy in various respects.

**Comment by mreineck** [comment]
I don't think we can make these modifications retroactively...
Not blaming you by any means, but rather the Ubuntu packagers: numpy 1.17 was released in July 2019, and scipy 1.4 in December 2019, so why didn't they end up in focal, which appeared in April 2020? Hmm, perhaps because numpy 1.17 dropped Python2 support ...

**Comment by gijzelaerr** [comment]
if you look at the discussion before then you will see we are saying the same thing and not much changed meanwhile. Nifty is not suited for inclusion in KERN-7, nor will it be suited for KERN-8 since that will also be based on Ubuntu focal. It's sad but I can't do much about this. Again I recommend sticking with the binary wheels. An alternative is to get a Debian package into Debian unstable, which will result in the package percolate into ubuntu at some point in the future, but that won't be part of KERN.

**Comment by landmanbester** [comment]
I don't really see the point of getting this into kern since it installs with pip. You can probably close the issue

**Comment by gijzelaerr** [comment]
ok, maybe we should try again for KERN-9. sorry!
