### ISSUE TITLE
pybdsm isn't correctly installed with the lofar package

### ISSUE THREAD

**Issue by Kitchi** [kernsuite/packaging#18]
After adding the KERN-1 repo, and installing the lofar package using ``apt-get install lofar``, the pybdsm program doesn't work.

When I try to run it, it says 

``
/usr/bin/python: can't open file '/usr/lib/python2.7/site-packages/lofar/bdsm/pybdsm.py': [Errno 2] No such file or directory 
``

The executable at `/usr/bin/pybdsm` seems to point to the above location, but the folder `site-packages` doesn't exist under `/usr/lib/python2.7`, but it does exist (and is empty) at `/usr/local/lib/python2.7`.

Running `locate lofar` doesn't seem to throw up anything either, even after a reboot.

**Comment by gijzelaerr** [comment]
This is a bug in the pybdsm script. The LOFAR people wrongly assumes the `pybdsm.py` file is always installed in that `site-packages` folder. As a workaround you can run:

`$ python /usr/lib/python2.7/dist-packages/lofar/bdsm/pybdsm.py`

Please report the bug at ASTRON, you can point them to this issue.

**Comment by gijzelaerr** [comment]
If LOFAR people read this, it doesn't really look like a good idea to call python from python. Why not just import the pybdsm stuff directly and run it from there. Or import pybdsm and figure out where the module is installed and then call python with that.

@Kitchi i'm closing this issue since it is not a problem with KERN, and you probably can go forward no with the command I supplied you.

**Comment by Kitchi** [comment]
@gijzelaerr Thanks for your prompt response! This solved the issue.
