### ISSUE TITLE
16.04 support seems to be broken

### ISSUE THREAD

**Issue by landmanbester** [kernsuite/packaging#209]
I only have the KERN-3 ppa and somehow I end up with kern4 and 5 packages when installing meqtrees related packages. See https://github.com/ska-sa/meqtrees-cattery/issues/101

**Comment by gijzelaerr** [comment]
hi! Thank you for your report. But you are misreading the version numbers. For example 1.5.0-1kern5 means there is a KERN specific revision of the package number 5 of software version 1.5.0. This is unrelated to the actual KERN version number. The repository has been unchanged for more than a year.

This looks to be an issue with the software you are using.  Please contact upstream author to find a fix for this issue. If an easy fix is available we might consider updating the package in KERN-3, but since this release is so old we prefer not to change it. I recommend you update to a more recent KERN.

I'm closing this issue for now, please reopen if you have a fix to propose.
