### ISSUE TITLE
libwsclean2 does not upgrade with wsclean

### ISSUE THREAD

**Issue by o-smirnov** [kernsuite/packaging#232]
I upgraded wsclean to 2.9, and it failed because libwsclean2 stayed at 2.6. A manual upgrade of the latter package fixed things, but isn't this something apt should be doing for me, if the dependencies are set correctly?

**Comment by gijzelaerr** [comment]
Is this an upgrade from KERN-5 to KERN-6? What is the error? if it is missing symbols or mismatching API's then it caused by upstream authors being too lazy to update their SO numbers, a recurring problem since they don't see the need to maintain them. @Athanaseus we Could report this upstream, but this just keeps on happening so not sure if there is a point to keep on repeating ourselves. Probably best to make the dependency relationship for the 2.9 package stricter by adding

`libwsclean2 ${binary:Version}`

here https://github.com/kernsuite-debian/wsclean/blob/master/debian/control#L28

**Comment by o-smirnov** [comment]
> Is this an upgrade from KERN-5 to KERN-6?

Correct. ``wsclean`` binary was missing some symbol. So yeah, old library.

**Comment by gijzelaerr** [comment]
@Athanaseus can you see if my proposed change works?

**Comment by gijzelaerr** [comment]
@Athanaseus was this change uplaoded?

**Comment by Athanaseus** [comment]
Yes, this is fixed.

**Comment by gijzelaerr** [comment]
awesome, thanks
