### ISSUE TITLE
add binary version for dependencies to packages, just like casacore package

### ISSUE THREAD

**Issue by gijzelaerr** [kernsuite/packaging#26]

**Comment by gijzelaerr** [comment]
@olebole do you know if it is possible to automatically force an upgrade of a dependency? Like in case of wsclean it was compiled to a newer casacore, but when you install wsclean with an old casacore installed it doesn't upgrade. It would be useful if we could do this with manual specification of the dependencies.

**Comment by olebole** [comment]
This refers to #27, right?
That is the idea of [transitions](https://wiki.debian.org/Teams/ReleaseTeam/Transitions), and this obviously went wrong with the new casacore: If the new casacore 2.2 is not ABI compatible to the old casacore 2.1, then 2.2 should get a new `SOVERSION` (and therefore also a new package name). This automatically solves the dependency problem: if wsclean is compiled against casacore-2.2, then it would be linked against the `libcasa-*2.2` packages and automatically install those. Packages compiled against the old version would have `libcasa-*2.1` as dependency, so everything works perfectly in this world.
As far as I remember, the casacore team claimed that there were no ABI incompatibilities (as 2.2 is just a bugfix over 2.1), therefore the `SOVERSION` remained unchanged.
What you could do as a temporary workaround is to require a newer version in the build dependency of wsclean. But be aware that this may break existing programs (which may be still linked to the old, binary-incompatible version).
So, there is no other clean way than to monitor the ABI compatibility and change the `SOVERSION` if the new version breaks it, and then to recompile everything with the new casacore package. In Debian (and Ubuntu), the latter is done automatically when the package name of the shared library changes.
n.b.: This is one of the disadvantages of maintaining a separate radio astronomy repository, since it may happen with any other dependency too, like wcslib, cfitsio or such.

**Comment by gijzelaerr** [comment]
ok, I already suspected the ABI change on the casacore side. I don't really feel like putting the effort in to work around the casacore problem, i'm just leaving it like this since it is a major issue and casacore development should take care of proper so version managed from now on, lesson learned.

**Comment by olebole** [comment]
BTW, if you have enough time to play with a quite exciting tool, you could try out the [upstream tracker](https://github.com/lvc/upstream-tracker), which does it automatically. For some time, the author maintained a web page where one could ask him to include the own libraries, and this worked very well. It is really a great tool! See f.e. the [hdf5 tracker](https://abi-laboratory.pro/tracker/timeline/hdf5/)
It looks that initial setup is simple, and one would just need to download development snapshots from github.

**Comment by gijzelaerr** [comment]
i'll have a look at that, thanks
