### ISSUE TITLE
chgcentre tool

### ISSUE THREAD

**Issue by rdeane** [kernsuite/packaging#9]
Phase rotates a given Measurement Set. Linked to wsclean, but not available (at least on jake/elwood). Would be be very useful to have it included in Kern. 

https://sourceforge.net/p/wsclean/wiki/chgcentre/

**Comment by gijzelaerr** [comment]
packaged up and uploaded to KERN-1 and KERN-DEV, should be available shortly

https://launchpad.net/~kernsuite/+archive/ubuntu/kern-dev/+build/10740576
https://launchpad.net/~kernsuite/+archive/ubuntu/kern-1/+build/10740577

note that jake/elwood don't run kern (yet) since KERN is based on Ubuntu 16.04.
