### ISSUE TITLE
Blank log and display window for CASA in KERN-3

### ISSUE THREAD

**Issue by shulevski** [kernsuite/packaging#91]
I have the KERN-3 image and whenever I try to start CASA while logged in it starts, however the log screen and other associated GUI windows (viewer) appear blank with no contents or possibility for interaction. My X11 mapping works, launching other GUI windows from the image works.

**Comment by gijzelaerr** [comment]
What image are you talking about?

Can you supply the command you are running? If I run `casa` from the casa package I get an IPython console.

**Comment by shulevski** [comment]
KERN-3. Indeed, if you run `casa` you get to the IPython console, but the log window which launches is blank and it should contain messages. Then, if you run the `viewer` task from the IPython prompt, you get screens launched, they are again blank, and they should contain the GUI interface.

**Comment by gijzelaerr** [comment]
I can't replicate the issue, see screenshot. This is starting CASA remotely on an Ubuntu 16.04 using the package without containerization. Are you running this inside a Docker container? The problem lies there probably. DId you try singularity?
<img width="1280" alt="screen shot 2018-03-19 at 10 19 25" src="https://user-images.githubusercontent.com/326308/37584675-1f14c768-2b5f-11e8-8960-0a0b28322385.png">

**Comment by shulevski** [comment]
Thanks. I am running it in a Docker container, I haven't tried Singularity. It is strange that CASA windows would be affected in such a way by running it in a Docker container.

**Comment by gijzelaerr** [comment]
it is probably some weird permission problem with a file in the homefolder.
